config/routes.rb
Rails.application.routes.draw do
  resources :chat_messages, except: [:new, :edit]
  resources :chats, except: [:new, :edit] do
    collection do
      get 'active_by_user/:user_id', to: "chats#active_by_user"
    end
    member do
      post 'block'
    end
  end
  resources :apparel_ratings, except: [:new, :edit]
  resources :property_groups, only: [:index]
  resources :global_tags, only: [:show]
  resources :apparel_tags, except: [:new, :edit]
  resources :apparel_images, except: [:new, :edit]
  resources :apparels, except: [:new, :edit] do
    collection do
      get 'owned'
      get 'matched'
    end
    member do
      post 'report'

      get '/remove_reported/:token', to: 'apparels#remove_reported', as: 'remove_reported'
    end
  end

  get 'apparels/apparels_by_user/:user_id', to: "apparels#apparels_by_user"
  get 'apparels/apparels_by_tag/:tag_id', to: "apparels#apparels_by_tag"

  post 'users/update_image', to: "users#update_image"
  post 'users/register_device', to: "users#register_device"
  post 'users/unregister_device', to: "users#unregister_device"
  post 'users/agreed_to_terms', to: "users#agreed_to_terms"
  post 'users/reset_password', to: "users#reset_password"

  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'overrides/registrations',
    omniauth_callbacks: "overrides/omniauth_callbacks"
  }

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq-dashboard'

  namespace :web do
    # devise_for :admins
    devise_for :users

    root to: "main#index"
    get 'logout', to: "main#logout"

    get 'users/heat_users', to: "users#heat_users"
    get 'users/heatmap', to: "users#heatmap"
    get 'users/heatcount', to: "users#heatcount"

    resources :global_tags, except: [:show, :destroy]
    resources :custom_notifications, except: [:edit, :update, :destroy] do
      member do
        post 'send', to: "custom_notifications#send_notification"
      end
    end
  end
end

app/models/custom_notification.rb
# == Schema Information
#
# Table name: custom_notifications
#
#  id           :integer          not null, primary key
#  push_title   :string           not null
#  push_message :string           not null
#  title        :string           not null
#  image_url    :string
#  body         :text
#  action_link  :string
#  action_title :string
#  sent_at      :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class CustomNotification < ActiveRecord::Base
  validates_presence_of :push_title, :push_message, :title

  def send_notification
    image = nil
    push_collapse_key = 'roupa_notification'
    extraData = { 
      title: self.title,
      image_url: self.image_url,
      action_link: self.action_link,
      action_title: self.action_title,
      body: self.body,
      type: 'custom' 
    }

    android_ids = Device.where(provider: 'android').map { |e| e.uid  }
    PushSender.instance.send_android_push(android_ids, self.push_title, self.push_message, image, push_collapse_key, extraData) if android_ids.length > 0

    ios_ids = Device.where(provider: 'ios').map { |e| e.uid  }
    PushSender.instance.send_ios_push(ios_ids, self.push_title, self.push_message, image, push_collapse_key, extraData) if ios_ids.length > 0

    self.sent_at = Time.now
    self.save
  end
end

app/controllers/web/custom_notifications_controller.rb
class Web::CustomNotificationsController < Web::ApplicationController
  before_action :set_custom_notification, only: [:send_notification, :show]

  # GET /custom_notifications
  # GET /custom_notifications.json
  def index
    @custom_notifications = CustomNotification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @custom_notifications }
    end
  end

  # GET /custom_notifications/1
  # GET /custom_notifications/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @custom_notifications }
    end
  end

  # GET /custom_notifications/new
  # GET /custom_notifications/new.json
  def new
    @custom_notification = CustomNotification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @custom_notification }
    end
  end

  # POST /custom_notifications
  # POST /custom_notifications.json
  def create
    @custom_notification = CustomNotification.new(custom_notification_params)

    respond_to do |format|
      if @custom_notification.save
        format.html { redirect_to web_custom_notifications_path, notice: 'Noticação criada.' }
        format.json { render json: @custom_notification, status: :created, location: web_custom_notifications_path }
      else
        format.html { render action: "new" }
        format.json { render json: @custom_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_notification
    respond_to do |format|
      if @custom_notification.send_notification
        format.html { redirect_to web_custom_notifications_path, notice: 'Noticação enviada.' }
        format.json { render json: @custom_notification, status: :created, location: web_custom_notifications_path }
      else
        format.html { render action: "show" }
        format.json { render json: @custom_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_custom_notification
      @custom_notification = CustomNotification.find(params[:id])
    end

    def custom_notification_params
      params.require(:custom_notification).permit(:push_title, :push_message, :title, :image_url, :action_title, :action_link, :body)
    end
end

app/views/web/custom_notifications/_form.html.erb
<style>
  .body-field-preview-container {
    height: 0;
    overflow: hidden;
    padding-top: 177%;
    position: relative;
    border: solid 1px #ccc;
  }
  .body-field-preview {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    padding: 10px;
  }
  .actions {
    margin-top: 10px;
  }
</style>
<%= form_for @custom_notification, url: (@custom_notification.new_record? ? web_custom_notifications_path : web_custom_notification_path(@custom_notification)), method: (@custom_notification.new_record? ? :post : :patch) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <% if @custom_notification.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@custom_notification.errors.count, "error") %> prohibited this custom_notification from being saved:</h2>

          <ul>
          <% @custom_notification.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group">
        <%= f.label :push_title, { class: 'col-form-label' } %>
        <%= f.text_field :push_title, { class: 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :push_message, { class: 'col-form-label' } %>
        <%= f.text_field :push_message, { class: 'form-control' } %>
      </div>

      <div class="field form-group">
        <%= f.label :title, { class: 'col-form-label' } %>
        <%= f.text_field :title, { class: 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :image_url, { class: 'col-form-label' } %>
        <%= f.text_field :image_url, { class: 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :action_title, { class: 'col-form-label' } %>
        <%= f.text_field :action_title, { class: 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :action_link, { class: 'col-form-label' } %>
        <%= f.text_field :action_link, { class: 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :body %>
        <%= f.text_area :body, { class: 'form-control body-field' } %>
      </div>
      <div class="actions text-right">
        <%= f.submit 'Salvar', :class => 'btn btn-space btn-primary' %>
        <%= link_to 'Cancelar', web_custom_notifications_path %>
      </div>
    </div>
    <div class="col-md-6">
      <label style="display:block">Preview</label>
      <div class="body-field-preview-container">
        <div class="body-field-preview"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/web/custom_notifications/index.html.erb
<div class="container-fluid dashboard-content">
  <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
          <div class="page-header">
              <h2 class="pageheader-title"></h2>
              <div class="page-breadcrumb">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="<%= web_root_path %>" class="breadcrumb-link">Dashboard</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Notificações</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </div>
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <!-- <div class="card-header d-flex"></div> -->
        <div class="card-body">
            <p id="notice"><%= notice %></p>
            <table class="table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>PUSH Título</th>
                  <th>Título</th>
                  <th>Enviada em</th>
                  <th colspan="1"></th>
                </tr>
              </thead>

              <tbody>
                <% @custom_notifications.each do |custom_notification| %>
                  <tr>
                    <td><%= custom_notification.id %></td>
                    <td><%= custom_notification.push_title %></td>
                    <td><%= custom_notification.title %></td>
                    <td><%= custom_notification.sent_at %></td>
                    <td><%= link_to 'Abrir', web_custom_notification_path(custom_notification) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= link_to 'Criar nova Notificação', new_web_custom_notification_path %>
        </div>
    </div>

    </div>
  </div>
</div>

app/views/web/custom_notifications/new.html.erb
<div class="container-fluid dashboard-content">
  <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
          <div class="page-header">
              <h2 class="pageheader-title"></h2>
              <div class="page-breadcrumb">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="<%= web_root_path %>" class="breadcrumb-link">Dashboard</a></li>
                          <li class="breadcrumb-item"><a href="<%= web_custom_notifications_path %>" class="breadcrumb-link">Notificações</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Nova</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </div>
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <h5 class="card-header">Nova</h5>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :bottom do %>
  <script>
    function debounce(func, wait, immediate) {
      var timeout;
      return function() {
        var context = this, args = arguments;
        var later = function() {
          timeout = null;
          if (!immediate) func.apply(context, args);
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) func.apply(context, args);
      };
    };
    $(document).ready(function() {
      $('.body-field').keyup( debounce(function changePreview() { 
        $('.body-field-preview').html($(this).val()); 
      }, 250));
    });
  </script>
<% end %>

app/views/web/custom_notifications/show.html.erb
<style>
  .body-field-preview-container {
    height: 0;
    overflow: hidden;
    padding-top: 177%;
    position: relative;
    border: solid 1px #ccc;
  }
  .body-field-preview {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    padding: 10px;
  }
  .actions {
    margin-top: 10px;
  }
</style>
<div class="container-fluid dashboard-content">
  <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
          <div class="page-header">
              <h2 class="pageheader-title"></h2>
              <div class="page-breadcrumb">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="<%= web_root_path %>" class="breadcrumb-link">Dashboard</a></li>
                          <li class="breadcrumb-item"><a href="<%= web_custom_notifications_path %>" class="breadcrumb-link">Notificações</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Ver</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </div>
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <h5 class="card-header">Ver</h5>
        <div class="card-body">
          <p id="notice"><%= notice %></p>

          <div class="row">
            <div class="col-md-6">
              <p>
                <strong>PUSH Título:</strong><br />
                <%= @custom_notification.push_title %>
              </p>

              <p>
                <strong>PUSH message:</strong><br />
                <%= @custom_notification.push_message %>
              </p>

              <p>
                <strong>Título:</strong><br />
                <%= @custom_notification.title %>
              </p>

              <p>
                <strong>Link Título:</strong><br />
                <%= @custom_notification.action_title %>
              </p>

              <p>
                <strong>Link URL:</strong><br />
                <%= @custom_notification.action_link %>
              </p>
              <div class="actions text-right">
                <%= form_for @custom_notification, url: send_web_custom_notification_path(@custom_notification), method: :post do |f| %>
                  <%= f.submit 'Enviar', :class => 'btn btn-space btn-primary' %>
                <% end %>
              </div>
            </div>
            <div class="col-md-6">
              <label style="display:block">Body (exibido no app)</label>
              <div class="body-field-preview-container">
                <div class="body-field-preview">
                  <%= @custom_notification.body ? @custom_notification.body.html_safe : '' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>