config/routes.rb
Rails.application.routes.draw do
  resources :chat_messages, except: [:new, :edit]
  resources :chats, except: [:new, :edit] do
    collection do
      get 'active_by_user/:user_id', to: "chats#active_by_user"
    end
    member do
      post 'block'
    end
  end
  resources :apparel_ratings, except: [:new, :edit]
  resources :property_groups, only: [:index]
  resources :global_tags, only: [:show]
  resources :apparel_tags, except: [:new, :edit]
  resources :apparel_images, except: [:new, :edit]
  resources :apparels, except: [:new, :edit] do
    collection do
      get 'owned'
      get 'matched'
    end
    member do
      post 'report'

      get '/remove_reported/:token', to: 'apparels#remove_reported', as: 'remove_reported'
    end
  end

  get 'apparels/apparels_by_user/:user_id', to: "apparels#apparels_by_user"
  get 'apparels/apparels_by_tag/:tag_id', to: "apparels#apparels_by_tag"

  post 'users/update_image', to: "users#update_image"
  post 'users/register_device', to: "users#register_device"
  post 'users/unregister_device', to: "users#unregister_device"
  post 'users/agreed_to_terms', to: "users#agreed_to_terms"
  post 'users/reset_password', to: "users#reset_password"

  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'overrides/registrations',
    omniauth_callbacks: "overrides/omniauth_callbacks"
  }

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq-dashboard'

  namespace :web do
    # devise_for :admins
    devise_for :users

    root to: "main#index"
    get 'logout', to: "main#logout"

    get 'users/heat_users', to: "users#heat_users"
    get 'users/heatmap', to: "users#heatmap"
    get 'users/heatcount', to: "users#heatcount"

    resources :global_tags, except: [:show, :destroy]
    resources :custom_notifications, except: [:edit, :update, :destroy] do
      member do
        post 'send', to: "custom_notifications#send_notification"
      end
    end
  end
end

app/models/global_tag.rb
# == Schema Information
#
# Table name: global_tags
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class GlobalTag < ActiveRecord::Base
  has_many :apparel_tags
end

app/controllers/global_tag_controller.rb
class GlobalTagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_global_tag, only: [:show, :destroy, :update]

  # GET /global_tags
  # GET /global_tags.json
  def index
    # Somente Admin
    # render json: GlobalTag.all
    render json: []
  end

  # GET /global_tags/1
  # GET /global_tags/1.json
  def show
    render json: @global_tag
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    head :no_content

    # Somente ADMIN
    # if @global_tag.update(global_tag_params)
    #   head :no_content
    # else
    #   render json: @global_tag.errors, status: :unprocessable_entity
    # end
  end

  # DELETE /global_tag/1
  # DELETE /global_tag/1.json
  def destroy
    # Somente Admin
    # @chat.destroy

    head :no_content
  end

  private

    def set_global_tag
      @global_tag = GlobalTag.find(params[:id])
    end

    def global_tag_params
      params.require(:global_tag).permit(:description, :body)
    end
end

app/controllers/global_tags_controller.rb
# == Schema Information
#
# Table name: global_tags
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class GlobalTagsController < APIController
  before_action :authenticate_user!
  before_action :set_global_tag, only: [:show]

  # GET /global_tags/1
  # GET /global_tags/1.json
  def show
    render json: @global_tag
  end

  private

    def set_global_tag
      @global_tag = GlobalTag.find(params[:id])
    end
end

app/controllers/web/global_tags_controller.rb
class Web::GlobalTagsController < Web::ApplicationController
  before_action :set_global_tag, only: [:show, :edit, :update, :destroy]

  # GET /global_tags
  # GET /global_tags.json
  def index
    if params[:all]
      @showing_all = true
      @global_tags = GlobalTag.all
    else
      @showing_all = false
      @global_tags = GlobalTag.where("(description is not null and description <> '') or (body is not null and body <> '')")
    end

    @global_tags = @global_tags
      .joins('left join apparel_tags on apparel_tags.global_tag_id = global_tags.id')
      .group(GlobalTag.column_names.map{|col| "global_tags.#{col}"})
      .order('COUNT(apparel_tags.id) DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @global_tags }
    end
  end

  # GET /global_tags/new
  # GET /global_tags/new.json
  def new
    @global_tag = GlobalTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @global_tag }
    end
  end

  # GET /global_tags/1/edit
  def edit
  end

  # POST /global_tags
  # POST /global_tags.json
  def create
    @global_tag = GlobalTag.new(create_global_tag_params)

    respond_to do |format|
      if @global_tag.save
        format.html { redirect_to web_global_tags_path, notice: 'Tag criada.' }
        format.json { render json: @global_tag, status: :created, location: web_global_tags_path }
      else
        format.html { render action: "new" }
        format.json { render json: @global_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /global_tags/1
  # PATCH/PUT /global_tags/1.json
  def update
    respond_to do |format|
      if @global_tag.update(update_global_tag_params)
        format.html { redirect_to web_global_tags_path, notice: 'Tag atualizada.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @global_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /global_tags/1
  # DELETE /global_tags/1.json
  def destroy
    @global_tag.destroy

    respond_to do |format|
      format.html { redirect_to web_global_tag_url }
      format.json { head :no_content }
    end
  end

  private

    def set_global_tag
      @global_tag = GlobalTag.find(params[:id])
    end

    def create_global_tag_params
      params.require(:global_tag).permit(:name, :description, :body)
    end

    def update_global_tag_params
      params.require(:global_tag).permit(:description, :body)
    end
end

app/views/web/global_tags/_form.html.erb
<style>
  .body-field-preview-container {
    height: 0;
    overflow: hidden;
    padding-top: 177%;
    position: relative;
    border: solid 1px #ccc;
  }
  .body-field-preview {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    padding: 10px;
  }
  .actions {
    margin-top: 10px;
  }
</style>
<%= form_for @global_tag, url: (@global_tag.new_record? ? web_global_tags_path : web_global_tag_path(@global_tag)), method: (@global_tag.new_record? ? :post : :patch) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <% if @global_tag.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@global_tag.errors.count, "error") %> prohibited this global_tag from being saved:</h2>

          <ul>
          <% @global_tag.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <% if @global_tag.new_record? %>
        <div class="field form-group">
          <%= f.label :name, { class: 'col-form-label' } %>
          <%= f.text_field :name, { class: 'form-control' } %>
        </div>
      <% end %>
      <div class="field form-group">
        <%= f.label :description, { class: 'col-form-label' } %>
        <%= f.text_field :description, { class: 'form-control' } %>
      </div>
      <div class="field form-group">
        <%= f.label :body %>
        <%= f.text_area :body, { class: 'form-control body-field' } %>
      </div>
      <div class="actions text-right">
        <%= f.submit 'Salvar', :class => 'btn btn-space btn-primary' %>
        <%= link_to 'Cancelar', web_global_tags_path %>
      </div>
    </div>
    <div class="col-md-6">
      <label style="display:block">Preview</label>
      <div class="body-field-preview-container">
        <div class="body-field-preview"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/web/global_tags/edit.html.erb
<div class="container-fluid dashboard-content">
  <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
          <div class="page-header">
              <h2 class="pageheader-title"></h2>
              <div class="page-breadcrumb">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="<%= web_root_path %>" class="breadcrumb-link">Dashboard</a></li>
                          <li class="breadcrumb-item"><a href="<%= web_global_tags_path %>" class="breadcrumb-link">Tags</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Editar</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </div>
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <h5 class="card-header">Editar #<%=@global_tag.name %></h5>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :bottom do %>
  <script>
    function debounce(func, wait, immediate) {
      var timeout;
      return function() {
        var context = this, args = arguments;
        var later = function() {
          timeout = null;
          if (!immediate) func.apply(context, args);
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) func.apply(context, args);
      };
    };
    $(document).ready(function() {
      $('.body-field').keyup( debounce(function changePreview() { 
        $('.body-field-preview').html($(this).val()); 
      }, 250));
    });
  </script>
<% end %>

app/views/web/global_tags/index.html.erb
<div class="container-fluid dashboard-content">
  <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
          <div class="page-header">
              <h2 class="pageheader-title"></h2>
              <div class="page-breadcrumb">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="<%= web_root_path %>" class="breadcrumb-link">Dashboard</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Tags</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </div>
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <div class="card-header d-flex">
          <h4 class="card-header-title">
            <%= @showing_all ? 'Todas Tags' : 'Tags Personalizadas' %>
          </h4>
          <div class="toolbar ml-auto">
              <% if !@showing_all %><a href="<%= web_global_tags_path %>?all=true" class="btn btn-primary btn-sm ">Ver Todas</a><% end %>
              <% if @showing_all %><a href="<%= web_global_tags_path %>" class="btn btn-primary btn-sm ">Ver Personalizadas</a><% end %>
          </div>
        </div>
        <div class="card-body">
            <p id="notice"><%= notice %></p>

            <table class="table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Nome</th>
                  <th>Personalizada?</th>
                  <th>Menções</th>
                  <th colspan="1"></th>
                </tr>
              </thead>

              <tbody>
                <% @global_tags.each do |global_tag| %>
                  <tr>
                    <td><%= global_tag.id %></td>
                    <td><%= global_tag.name %></td>
                    <td><%= !global_tag.description.blank? || !global_tag.body.blank? ? 'Sim' : '' %></td>
                    <td><%= global_tag.apparel_tags.count %></td>
                    <!-- <td><%= link_to 'Ver', web_global_tag_path(global_tag) %></td> -->
                    <td><%= link_to 'Editar', edit_web_global_tag_path(global_tag) %></td>
                    <!-- <td><%= link_to 'Apagar', web_global_tag_path(global_tag), method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= link_to 'Criar Tag nova', new_web_global_tag_path %>
        </div>
    </div>

    </div>
  </div>
</div>

app/views/web/global_tags/new.html.erb
<div class="container-fluid dashboard-content">
  <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
          <div class="page-header">
              <h2 class="pageheader-title"></h2>
              <div class="page-breadcrumb">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="<%= web_root_path %>" class="breadcrumb-link">Dashboard</a></li>
                          <li class="breadcrumb-item"><a href="<%= web_global_tags_path %>" class="breadcrumb-link">Tags</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Nova</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </div>
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <h5 class="card-header">Nova</h5>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :bottom do %>
  <script>
    function debounce(func, wait, immediate) {
      var timeout;
      return function() {
        var context = this, args = arguments;
        var later = function() {
          timeout = null;
          if (!immediate) func.apply(context, args);
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) func.apply(context, args);
      };
    };
    $(document).ready(function() {
      $('.body-field').keyup( debounce(function changePreview() { 
        $('.body-field-preview').html($(this).val()); 
      }, 250));
    });
  </script>
<% end %>